---
development:
  dialect: postgres
  database: postgres
  user: richard
  password: password
  host: 10.0.131.12
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://richard:password@10.0.131.12:5432/app?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://richard:password@10.0.131.12:5432/app?sslmode=disable"}}
